// SPDX-License-Identifier: MPL-2.0
package io.advancex.app.ui.settings

import android.app.AlertDialog
import android.content.Intent
import android.os.Bundle
import android.widget.LinearLayout
import io.advancex.app.R
import io.advancex.app.data.GameEntry
import io.advancex.app.ui.common.BaseActivity
import io.advancex.app.ui.common.TextStyle
import io.advancex.app.ui.common.add
import io.advancex.app.ui.common.card
import io.advancex.app.ui.common.secondaryButton
import io.advancex.app.ui.common.sectionHeader
import io.advancex.app.ui.common.settingRow
import io.advancex.app.ui.common.statusBadge
import io.advancex.app.ui.common.switchRow
import io.advancex.app.ui.common.text
import io.advancex.engine.AdvanceX
import io.advancex.engine.graphics.FeatureStatus
import io.advancex.engine.mods.ModPackager
import io.advancex.engine.studio.StudioTool
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.File

/** Advance Studio: pack-creation tools (asset capture and .advx export today). */
class StudioActivity : BaseActivity() {
    private lateinit var column: LinearLayout
    private var exportGame: GameEntry? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        column = contentColumn {}
        setScreen(getString(R.string.studio_title), column)
    }

    override fun onResume() {
        super.onResume()
        render()
    }

    private fun render() {
        column.removeAllViews()
        column.addView(text(getString(R.string.studio_intro), TextStyle.BODY_SECONDARY))
        column.add(switchRow(getString(R.string.studio_capture), getString(R.string.studio_capture_body),
            services.settings.value.captureSprites, R.drawable.ic_studio, statusBadge(FeatureStatus.EXPERIMENTAL)) { on ->
            services.settings.update { it.copy(captureSprites = on) }
        }, topMarginDp = 16)

        val captured = services.library.games.map { it to services.studio.count(it.id) }.filter { it.second > 0 }
        if (captured.isNotEmpty()) {
            column.addView(sectionHeader("Captures"))
            for ((game, count) in captured) {
                column.add(card {
                    addView(text(getString(R.string.studio_captured, count, game.title), TextStyle.HEADLINE))
                    add(text(getString(R.string.studio_location, "studio/${game.id}/"), TextStyle.CAPTION), topMarginDp = 4)
                    add(secondaryButton(getString(R.string.studio_export), R.drawable.ic_mods) { export(game) }, topMarginDp = 10)
                }, bottomMarginDp = 8)
            }
        }

        column.addView(sectionHeader("Tools"))
        for (tool in StudioTool.entries) {
            column.add(settingRow(tool.title, tool.description, badge = statusBadge(tool.status)), bottomMarginDp = 8)
        }
    }

    /** Builds an installable draft pack from captured sprites and lets the user save it. */
    private fun export(game: GameEntry) {
        exportGame = game
        val intent = Intent(Intent.ACTION_CREATE_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE)
            .setType("application/octet-stream").putExtra(Intent.EXTRA_TITLE, "${game.id}-hd-draft.advx")
        @Suppress("DEPRECATION")
        startActivityForResult(intent, REQUEST_EXPORT)
    }

    @Deprecated("Deprecated in Java")
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        val uri = data?.data
        val game = exportGame
        if (requestCode != REQUEST_EXPORT || resultCode != RESULT_OK || uri == null || game == null) return
        scope.launch {
            val result = withContext(Dispatchers.IO) {
                runCatching {
                    val dir = File(cacheDir, "studio-export").apply { deleteRecursively(); mkdirs() }
                    val sprites = File(dir, "sprites").apply { mkdirs() }
                    val keys = services.studio.spritesDir(game.id).listFiles { f -> f.name.endsWith(".png") }!!.map { f ->
                        f.copyTo(File(sprites, f.name))
                        f.nameWithoutExtension
                    }
                    val profileId = "${game.id.lowercase()}_hd".replace(Regex("[^a-z0-9._-]"), "_")
                    File(dir, "manifest.json").writeText(
                        """
                        {
                          "name": "${game.title.replace("\"", "'")} HD (draft)",
                          "version": "0.1.0",
                          "author": "",
                          "description": "Draft generated by Advance Studio. Replace the PNG files in sprites/ with high-resolution artwork.",
                          "compatibleGames": [ { "gameCode": "${game.gameCode}", "sha1": "${game.sha1}" } ],
                          "advanceXVersion": ">=${AdvanceX.VERSION}"
                        }
                        """.trimIndent(),
                    )
                    val profileDir = File(dir, "profiles/$profileId").apply { mkdirs() }
                    File(profileDir, "profile.json").writeText(
                        """
                        {
                          "name": "${game.title.replace("\"", "'")} HD (draft)",
                          "romHash": "${game.sha1}",
                          "enhancements": { "spriteReplacement": true },
                          "replacements": ["replacements.json"]
                        }
                        """.trimIndent(),
                    )
                    File(profileDir, "replacements.json").writeText(
                        "{\n  \"kind\": \"sprite\",\n  \"entries\": [\n" +
                            keys.joinToString(",\n") { "    { \"key\": \"$it\", \"file\": \"../../sprites/$it.png\" }" } +
                            "\n  ]\n}\n",
                    )
                    val out = File(cacheDir, "studio-export.advx")
                    ModPackager.pack(dir, out)
                    contentResolver.openOutputStream(uri)?.use { o -> out.inputStream().use { it.copyTo(o) } }
                    keys.size
                }
            }
            result.onSuccess { toast("Exported ${it} sprites") }
                .onFailure { AlertDialog.Builder(this@StudioActivity).setMessage(it.message).setPositiveButton(android.R.string.ok, null).show() }
        }
    }

    companion object {
        private const val REQUEST_EXPORT = 4701
    }
}
