// SPDX-License-Identifier: MPL-2.0
package io.advancex.core.saves

import java.io.File

/**
 * On-disk layout of everything a player can lose:
 *
 * ```
 * saves/
 * └── <GAME_ID>/
 *     ├── cartridge/
 *     │   ├── game.sav          battery save (same format as desktop mGBA)
 *     │   ├── game.sav.bak      previous generation, kept on every write
 *     │   └── backups/          rotating timestamped snapshots
 *     ├── states/
 *     │   ├── slot1.axstate ... slot9.axstate
 *     │   └── auto.axstate      optional autosave on exit
 *     └── screenshots/
 *         └── slot1.png ...     thumbnails for save states
 * ```
 */
class SaveLayout(val root: File) {
    fun gameDir(gameId: String) = File(root, sanitize(gameId))
    fun cartridgeDir(gameId: String) = File(gameDir(gameId), "cartridge")
    fun cartridgeSave(gameId: String) = File(cartridgeDir(gameId), "game.sav")
    fun cartridgeBackupsDir(gameId: String) = File(cartridgeDir(gameId), "backups")
    fun statesDir(gameId: String) = File(gameDir(gameId), "states")
    fun screenshotsDir(gameId: String) = File(gameDir(gameId), "screenshots")

    fun stateFile(gameId: String, slot: StateSlot) = File(statesDir(gameId), "${slot.fileStem}.axstate")
    fun screenshotFile(gameId: String, slot: StateSlot) = File(screenshotsDir(gameId), "${slot.fileStem}.png")

    /** Creates all directories for a game. Returns false if storage is unavailable. */
    fun ensureDirs(gameId: String): Boolean =
        listOf(cartridgeDir(gameId), statesDir(gameId), screenshotsDir(gameId), cartridgeBackupsDir(gameId))
            .all { it.isDirectory || it.mkdirs() }

    companion object {
        /** Game ids are generated by AdvanceX, but never trust them as paths. */
        fun sanitize(gameId: String): String {
            val clean = gameId.map { if (it.isLetterOrDigit() || it == '_' || it == '-') it else '_' }.joinToString("")
            return clean.ifEmpty { "unknown" }.take(64)
        }
    }
}

/** Save-state slots. Slot 0 is the automatic save-on-exit slot. */
@JvmInline
value class StateSlot(val index: Int) {
    init {
        require(index in 0..MAX) { "slot must be 0..$MAX" }
    }

    val isAuto: Boolean get() = index == 0
    val fileStem: String get() = if (isAuto) "auto" else "slot$index"
    val label: String get() = if (isAuto) "Auto" else "Slot $index"

    companion object {
        const val MAX = 9
        val AUTO = StateSlot(0)
        val manual: List<StateSlot> = (1..MAX).map { StateSlot(it) }
    }
}
